// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkdoffcbosaqlsrxmiro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZG9mZmNib3NhcWxzcnhtaXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzEzOTAsImV4cCI6MjA2Mjk0NzM5MH0.osIqyWaBHmZd-xAieiZIb-YrvxIgPv6OZyB_ONI-LCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);